[workspace]
resolver = "2"

members = [
    "assemble-initramfs", 
    "cpio"
]

[workspace.dependencies]
clap = "4.4.11"
rand = "0.8.5"
slog = "2.7.0"
slog-async = "2.8.0"
slog-json = "2.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
