libraries:
  - /lib64/ld-linux-x86-64.so.2
binaries:
  - ./target/x86_64-unknown-linux-musl/debug/qsh
  - ./target/x86_64-unknown-linux-musl/debug/ls
  - ./target/x86_64-unknown-linux-musl/debug/login
  - ./target/x86_64-unknown-linux-musl/debug/cat
  - ./target/x86_64-unknown-linux-musl/debug/clear
  - ./target/x86_64-unknown-linux-musl/debug/busctl
secure_binaries:
  - ./target/x86_64-unknown-linux-musl/debug/qinit
  - ./target/x86_64-unknown-linux-musl/debug/loggerd
  - ./target/x86_64-unknown-linux-musl/debug/getty
  - ./target/x86_64-unknown-linux-musl/debug/udevd
  - ./target/x86_64-unknown-linux-musl/debug/busd
files:
  etc/passwd: configs/passwd
  etc/shadow: configs/shadow
  etc/group: configs/group
  /etc/qinit/services: configs/services
  /home/colin: configs/home
output_file: ./target/filesystem.ext4
