libraries:
  - /lib64/ld-linux-x86-64.so.2
binaries:
  - ./target/x86_64-unknown-linux-musl/debug/qsh
  - ./target/x86_64-unknown-linux-musl/debug/ls
  - ./target/x86_64-unknown-linux-musl/debug/login
secure_binaries:
  - ./target/x86_64-unknown-linux-musl/debug/qinit
  - ./target/x86_64-unknown-linux-musl/debug/getty
files:
  etc/passwd: configs/passwd
  etc/shadow: configs/shadow
  etc/group: configs/group
output_file: ./target/filesystem.ext4
