[package]
name = "net"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "netc"
path = "src/bin/netc/main.rs"

[dependencies]
netlink = { path = "../netlink" }
clap = { workspace = true }
tables = { path = "../tables" }